# Generated by Django 5.1.7 on 2025-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_verify',
            name='verify',
        ),
        migrations.AddField(
            model_name='email_verify',
            name='token',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
